export const planets = [
    {
        name: 'Mercury',
        radius: 0.38,
        tilt: 0,
        distance: 5,
        orbitEccentricity: 0.2056,
        orbitInclination: 7,
        orbitPeriod: 50 * 0.24,
        rotationPeriod: 50 / 58.6,
        texture: 'textures/mercury.jpg',
    },
    {
        name: 'Venus',
        radius: 0.95,
        tilt: 177.3,
        distance: 7.5,
        orbitEccentricity: 0.0068,
        orbitInclination: 3.4,
        orbitPeriod: 50 * 0.62,
        rotationPeriod: 50 / -243,
        texture: 'textures/venus.jpg',
    },
    {
        name: 'Earth',
        radius: 1,
        tilt: 23.4,
        distance: 10,
        orbitEccentricity: 0.0167,
        orbitInclination: 0,
        orbitPeriod: 50,
        rotationPeriod: 50 / 1,
        texture: 'textures/earth.jpg',
    },
    {
        name: 'Mars',
        radius: 0.53,
        tilt: 25.2,
        distance: 15,
        orbitEccentricity: 0.0934,
        orbitInclination: 1.9,
        orbitPeriod: 50 * 1.88,
        rotationPeriod: 50 / 1.03,
        texture: 'textures/mars.jpg',
    },
];
